name: EMFPinata
version: '${project.version}'
main: uk.firedev.emfpinata.EMFPinata
api-version: '1.21'
author: FireML
description: ${project.description}
folia-supported: true
dependencies:
  server:
    EvenMoreFish:
      required: true
      load: BEFORE